package org.assertj.db.type;

import java.io.PrintWriter;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;

import javax.sql.DataSource;

import org.assertj.db.common.AbstractTest;
import org.assertj.db.error.AssertJDBException;
import org.junit.Test;

/**
 * Test on loading of the data and exception during the closing.
 * 
 * @author Régis Pouiller
 * 
 */
public class AbstractDbData_Exception_Test extends AbstractTest {

  /**
   * This method should fail because the connection throw an exception.
   */
  @Test(expected = AssertJDBException.class)
  public void should_fail_because_connection_throws_exception() {
    DataSource ds = new DataSource() {

      @Override
      public PrintWriter getLogWriter() throws SQLException {
        return null;
      }

      @Override
      public void setLogWriter(PrintWriter out) throws SQLException {

      }

      @Override
      public void setLoginTimeout(int seconds) throws SQLException {

      }

      @Override
      public int getLoginTimeout() throws SQLException {
        return 0;
      }

      @Override
      public <T> T unwrap(Class<T> iface) throws SQLException {
        return null;
      }

      @Override
      public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return false;
      }

      @Override
      public Connection getConnection() throws SQLException {
        return new Connection() {

          @Override
          public <T> T unwrap(Class<T> iface) throws SQLException {
            return null;
          }

          @Override
          public boolean isWrapperFor(Class<?> iface) throws SQLException {
            return false;
          }

          @Override
          public void setTypeMap(Map<String, Class<?>> map) throws SQLException {

          }

          @Override
          public void setTransactionIsolation(int level) throws SQLException {

          }

          @Override
          public Savepoint setSavepoint(String name) throws SQLException {
            return null;
          }

          @Override
          public Savepoint setSavepoint() throws SQLException {
            return null;
          }

          @Override
          public void setReadOnly(boolean readOnly) throws SQLException {
          }

          @Override
          public void setHoldability(int holdability) throws SQLException {
          }

          @Override
          public void setClientInfo(String name, String value) throws SQLClientInfoException {
          }

          @Override
          public void setClientInfo(Properties properties) throws SQLClientInfoException {
          }

          @Override
          public void setCatalog(String catalog) throws SQLException {
          }

          @Override
          public void setAutoCommit(boolean autoCommit) throws SQLException {
          }

          @Override
          public void rollback(Savepoint savepoint) throws SQLException {
          }

          @Override
          public void rollback() throws SQLException {
          }

          @Override
          public void releaseSavepoint(Savepoint savepoint) throws SQLException {
          }

          @Override
          public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
              int resultSetHoldability) throws SQLException {
            return null;
          }

          @Override
          public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
              throws SQLException {
            return null;
          }

          @Override
          public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
            return null;
          }

          @Override
          public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
            return null;
          }

          @Override
          public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
            return null;
          }

          @Override
          public PreparedStatement prepareStatement(String sql) throws SQLException {
            return null;
          }

          @Override
          public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
              int resultSetHoldability) throws SQLException {
            return null;
          }

          @Override
          public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
              throws SQLException {
            return null;
          }

          @Override
          public CallableStatement prepareCall(String sql) throws SQLException {
            return null;
          }

          @Override
          public String nativeSQL(String sql) throws SQLException {
            return null;
          }

          @Override
          public boolean isValid(int timeout) throws SQLException {
            return false;
          }

          @Override
          public boolean isReadOnly() throws SQLException {
            return false;
          }

          @Override
          public boolean isClosed() throws SQLException {
            return false;
          }

          @Override
          public SQLWarning getWarnings() throws SQLException {
            return null;
          }

          @Override
          public Map<String, Class<?>> getTypeMap() throws SQLException {
            return null;
          }

          @Override
          public int getTransactionIsolation() throws SQLException {
            return 0;
          }

          @Override
          public DatabaseMetaData getMetaData() throws SQLException {
            return null;
          }

          @Override
          public int getHoldability() throws SQLException {
            return 0;
          }

          @Override
          public String getClientInfo(String name) throws SQLException {
            return null;
          }

          @Override
          public Properties getClientInfo() throws SQLException {
            return null;
          }

          @Override
          public String getCatalog() throws SQLException {
            return null;
          }

          @Override
          public boolean getAutoCommit() throws SQLException {
            return false;
          }

          @Override
          public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
            return null;
          }

          @Override
          public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
              throws SQLException {
            return null;
          }

          @Override
          public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
            return null;
          }

          @Override
          public Statement createStatement() throws SQLException {
            throw new SQLException();
          }

          @Override
          public SQLXML createSQLXML() throws SQLException {
            return null;
          }

          @Override
          public NClob createNClob() throws SQLException {
            return null;
          }

          @Override
          public Clob createClob() throws SQLException {
            return null;
          }

          @Override
          public Blob createBlob() throws SQLException {
            return null;
          }

          @Override
          public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
            return null;
          }

          @Override
          public void commit() throws SQLException {
          }

          @Override
          public void close() throws SQLException {
            throw new SQLException();
          }

          @Override
          public void clearWarnings() throws SQLException {
          }
        };
      }

      @Override
      public Connection getConnection(String username, String password) throws SQLException {
        return null;
      }

    };
    Table table = new Table(ds, "movi");
    table.getColumnsNameList();
  }
}
